### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Iriscys** [INFO-526-SU24/final-project-DataDuo#1]
The following is the peer review of the project proposal by Iris Sum @Iriscys.

- Describe the goal of the project.
To analyze the changes in US polling places over the period from 2012 to 2020 by nations and states, as well as the difference between urban and rural areas. 

- Describe the data used or collected.
The dataset polling_places.csv contains information on US polling places from 2012 to 2020, including locations, years active, demographic information of precincts, voter turnout , etc.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Question 1 : Probably a line chart with years on the x-axis and number of polling places on the y-axis to show the trends in the number of polling places over time. 
Question 2 : Group the data by area type, and show the distribution of polling places between urban and rural areas with state and election date.

- Is there anything that is unclear from the proposal?
The proposal is clear to understand. It would be better to add "Plan of attack" to show team work distribution. The source of dataset (eg. from which organization) may also be included in Dataset section. 

- Provide constructive feedback on how the team might be able to improve their project.
There are several ways to plot question 2, eg. bar chart, map by year (color by area type, brightness by votes count,..). It would be better to clarify what type of plots will be used for illustrating the questions. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
It will be question 2 since question 1 is a more straight forward one. 

- Provide constructive feedback on any issues with file and/or code organization.
May update the package loading code with pacman::p_load.

- (Optional) Any further comments or feedback?

**Comment by ld793** [comment]
Plan of attack added. Adding type of plots and calculated variables. Also modifying code to include pacman::p_load().
