### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by dwiesneraz** [INFO-526-SU24/final-project-DataDuo#2]
The following is the peer review of the project proposal by Daniel Wiesner. The team members that participated in this review are 

- Daniel Wiesner - @dwiesneraz

- Describe the goal of the project.

The goal is to analyze trends in polling places across the US from 2012 to 2020, focusing on the number of polling places across states and comparisons of urban and rural areas.

- Describe the data used or collected.

The data is comprised of records of information about polling places in the US from 2012 to 2020. The data includes location and time information, along with voter turnout and demographic information.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

Question 1:
 - extract the year from the date field and group by years to get a count of polling places each year.
 - plot number of polling places over the years.

Question 2:
 - classify each polling place as urban or rural based on location, then group by area type to get a count of polling places by state, area, and election period.
 - calculate and compare voter turnouts between rural and urban areas.

- Is there anything that is unclear from the proposal?

I do not believe that there is any information that is specifically unclear. The general analysis plan for each question is good but it would benefit from a proper weekly plan of attack as is included in the assignment spec.

- Provide constructive feedback on how the team might be able to improve their project.

I think it would be helpful for you to clarify what types of plots you plan to use or experiment with for each question. For example: you may want to consider mapping the results of one or both of these analyses onto an actual map of the US. This would make it easy to display all of the information for each state without being overcrowded. The professor provided examples of this in the 'Project Examples' section of the course page. You could color code states by area type majority or use a gradient for area type proportion or something similar.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

I am most interested in the differences in voting place availability and voter turnout between rural and urban areas. I would like to see that highlighted in some capacity similar to what I have described in the last section.

- Provide constructive feedback on any issues with file and/or code organization.

It would be best to convert your package loading section to the professor's pacman::p_load() format.

I think it would be helpful for you to add a 'Setup' header in the package install/load section. 

I assume that you were trying to create subheadings in the 'Analysis plan' and 'Dataset' sections with the #'s. I would recommend going back and fixing them so that they render correctly. I think the issue is that you added them in the Visual view of the file when you actually need to add them in the Source view so that they don't get escaped.

As stated in the clarity section, you are missing a weekly plan of attack section which is included in the spec.

- (Optional) Any further comments or feedback?

**Comment by ld793** [comment]
Plan of attack added. Adding type of plots and calculated variables. Also modifying code to include pacman::p_load().
